### ISSUE TITLE
part of tthe page working some of it not

### ISSUE THREAD

**Issue by elleanorrripley** [georgyangelov/Dark-youtube-plugin-chrome#46]
Prts of the main page are working and only half of the page during videos not working I've included screenshots
![untitled2](https://cloud.githubusercontent.com/assets/23110301/19789971/3eee11ec-9c82-11e6-8f53-f05e2b380d56.jpg)
![untitled2 1](https://cloud.githubusercontent.com/assets/23110301/19789974/457b18ca-9c82-11e6-816b-fc5ce992c7bd.jpg)

**Comment by Dancanplay** [comment]
Are you using any other extensions that could conflict with our extension. Try temporarily disabling conflicting extensions and see if it works out for you.

**Comment by Dancanplay** [comment]
"Magic Actions for Youtube" is conflicting with our extension, you either disable the conflicting extension or adjust it.
Closing the issue.
