### ISSUE TITLE
Centered Search

### ISSUE THREAD

**Issue by NSDex** [georgyangelov/Dark-youtube-plugin-chrome#50]
Youtube appears to be testing out a new centered search field.  Selector is ".exp-searchbox-redesign #masthead-search", so this is likely experimental.

![option0](https://cloud.githubusercontent.com/assets/2069299/23051475/21543c5c-f47e-11e6-831a-e63c5199f559.png)

I've played with a couple of options for the styling.  Not sure which I prefer.

`
.exp-searchbox-redesign #masthead-search {
	background-color: #1b1b1b !important;
}
`
![option1](https://cloud.githubusercontent.com/assets/2069299/23051504/5fe762d2-f47e-11e6-925d-f61c7e0087c3.png)

`
.exp-searchbox-redesign #masthead-search {
	background-color: #272727 !important;
}
`
![option3](https://cloud.githubusercontent.com/assets/2069299/23051514/8ef1ba78-f47e-11e6-9d0a-767ad2ce17cf.png)

`
.exp-searchbox-redesign #masthead-search {
	background-color: #222 !important;
	border: solid 1px #666 !important;
	height: 24px !important;
	margin-top: 6px !important;
}
.exp-searchbox-redesign #masthead-search:before {
	top: 5px !important;
}
.exp-searchbox-redesign #masthead-search-terms {
	margin: 0px !important;
}
`
![option2](https://cloud.githubusercontent.com/assets/2069299/23051523/9d8ef53c-f47e-11e6-9ce7-e88d14e2b9fe.png)

The last one recaptures the outline that is present in the current styling, but I had to adjust the heights and margins of some of the inner elements - which I don't like.

**Comment by Dancanplay** [comment]
I would rather go with the first option, adding this @688:
`#masthead-search-terms:not(.exp-searchbox-redesign #masthead-search)`
![first](https://cloud.githubusercontent.com/assets/9385112/23065865/f9739ce2-f517-11e6-9400-135d2a09d401.PNG)
