### ISSUE TITLE
Delay of dark theme when opening Youtube

### ISSUE THREAD

**Issue by reviants** [georgyangelov/Dark-youtube-plugin-chrome#55]
Hi, 
since yesterday 27/04/2017, whenever I load or refresh Youtube there is a 2-3 seconds delay before the dark theme is applied. This did not happen previously. Could it be related to the update?

**Comment by georgyangelov** [comment]
Thanks for the report! Just looked into it and released a fix. Can you check now? Reopen the issue if still present on v2.0.1

**Comment by reviants** [comment]
When will v2.0.1 be released though? I've been using an alternative extension in the meanwhile because Youtube flashing in white at each reload was a dealbreaker. Still patiently waiting though (because I prefer your extension's colour scheme to others)

**Comment by georgyangelov** [comment]
It is already released. Can you check your version and manually update if needed?
