### ISSUE TITLE
YouTube Redesign - Bright white comments section and playlists

### ISSUE THREAD

**Issue by Noyztank** [georgyangelov/Dark-youtube-plugin-chrome#58]
Redesigned as of 8-30-17. Front page and various menus seem fine, comments section is now white along with most of the page when viewing an entire playlist
![white comments section](https://user-images.githubusercontent.com/31495105/29902476-4b0e0162-8db3-11e7-962c-c1eb21086c7b.png)
![white playlist](https://user-images.githubusercontent.com/31495105/29902564-bc574612-8db3-11e7-80d1-ebc315a93c1c.png)

**Comment by calvertdw** [comment]
Same here.
![image](https://user-images.githubusercontent.com/1161586/29905062-fa3b912c-8dd1-11e7-8aaa-daf3c14c3010.png)

**Comment by georgyangelov** [comment]
Hey! The new YouTube design has a built-in dark theme. You can turn off the extension, click on your profile icon and there is a Dark Theme option.

I will not be supporting the extension unless they somehow decide to remove the built-in one.

**Comment by Noyztank** [comment]
Sweet thanks, didn't notice that

**Comment by calvertdw** [comment]
Welp. That's cool. Sorry about your plugin!
