### ISSUE TITLE
This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by AlvyPiper** [georgyangelov/Dark-youtube-plugin-chrome#61]
So what in their policy changed that caused them to disable this extension, or did this extension do some malicious stuff 🤔

**Comment by georgyangelov** [comment]
Their design changed, which made this extension obsolete as they have dark mode built-in. It provides no significant benefit. Also, it had some issues working with the new design, so I decided to disable it myself.

No malicious stuff, as you can see yourself from the code :)

**Comment by georgyangelov** [comment]
It was nice while it lasted :)

**Comment by AlvyPiper** [comment]
It's unfortunate that Google said it violated the terms of service rather than the author removed it himself, I'm not (and never was) trying to paint you as doing malicious stuff, if it seemed that way it was not as I intended, it's just unfortunate that in the past many solo devs/groups have sold their extensions to phishy companies who decided to use it for malicious use. I see why you got rid of the app, but having to use new YouTube, as a result, is eh. 

Thanks for the reply, and thank you for the years spent developing this app nonetheless.
